version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser
      - POSTGRES_DB=test_db
  dbmate:
    image: amacneil/dbmate
    command: -d "/backend/migrations" up
    depends_on:
      - db
    volumes:
      - ./migrations:/backend/migrations
    environment:
      - DATABASE_URL=postgres://testuser:testuser@db:5432/test_db?sslmode=disable
      - DBMATE_MIGRATIONS_DIR=backend/migrations
volumes:
  postgres_data:
